### ISSUE TITLE
HTTP handler blows up event loop in case of errors

### ISSUE THREAD

**Issue by kelunik** [noerosell/awsyncronic#2]
https://github.com/noerosell/awsyncronic/blob/5476abac80a830e94a8eb3ca74d448dcd2e63484/lib/AwsHttpHandler.php#L43-L56

^ That code will throw any exception into the event loop, resulting in the loop stopping in case no error handler is set. Instead, the exception should be caught there and reject the Guzzle promise.

**Comment by noerosell** [comment]
thanks @kelunik !!
